### ISSUE TITLE
Unit format is misleading

### ISSUE THREAD

**Issue by jammi** [bitnbytesio/node-input-validator#23]
For instance kb means kilobit, mb means millibit. You're using them for kilobyte and megabit. These units are case-sensitive and you should treat them like that.

**Comment by jammi** [comment]
Also, mega = 10^6 = 1000000, kilo = 10^3 = 1000. Ki = 2^10 = 1024, Mi = 2^20 = 1048576.

**Comment by bitnbytesio** [comment]
Hi after long discussions and suggestion from many users, I decided to go with using case in-sensitive notations. Already added b(Bytes),kb/k(KilloBytes),mb/m(MegaBytes),gb/g(GigaBytes). in documentation under size rule to avoid confusion.

**Reason to not treat these units as case-sensitive**
As package supports declaring rules in string notation (size:4kb), forcing user to use KB instead of kb opens room for more mistakes. As package only support byte units, no matter if end user use kb or KB or Kb. Package always treat or validate size in bytes, so it's not fair to force users to use SHIFT or Caps Lock key (to type KB instead of kb).

However If in future, package introduce some rules that use bits too, then may consider treating units as they are.

Thanks for raising this point. You are always welcomed.
